### ISSUE TITLE
double free or corruption (out) when running test data 

### ISSUE THREAD

**Issue by wwtinwhu** [APRIL-ZJU/Coco-LIC#6]
Hi, @Jerry-locker !

I followed the same environment and third party version as listed in the README. However, it died with a double free problem.

At first I thought it was because pcl did not turn off MARCH_NATIVE when compiling. After I turned off this option and recompiled, the memory error still occurred. Any suggestions? Thanks! 
![截图 2024-05-09 16-48-54](https://github.com/APRIL-ZJU/Coco-LIC/assets/28035224/91bb6e2b-5d52-461b-ab71-18d298ac08d5)

**Comment by zyj360507603** [comment]
+1

**Comment by tsuibeyond** [comment]
+1

**Comment by cxjbill** [comment]
+1

**Comment by lojmkjd** [comment]
有人解决了这个问题吗

**Comment by Geyuwen** [comment]
是内存泄漏的问题，gdb调试一下
修改代码：
#将/root/catkin_coco/src/Coco-LIC/src/odom/factor/analytic_diff/marginalization_factor.cpp修改如下：
// MarginalizationInfo::~MarginalizationInfo() {
//   for (auto it = parameter_block_data.begin(); it != parameter_block_data.end();
//        ++it) {
//     delete it->second;
//   }

//   for (int i = 0; i < (int)factors.size(); i++) {
//     delete factors[i]->cost_function;
//     delete factors[i];
//   }
// }

MarginalizationInfo::~MarginalizationInfo() {
  // 1. 移除对 parameter_block_data 中数据的删除
  //    因为这些数据很可能就是 Ceres Problem 正在管理的参数块
  // for (auto it = parameter_block_data.begin(); it != parameter_block_data.end();
  //      ++it) {
  //   delete it->second; // <-- 移除这行，或者检查 it->second 是否是你自己 new 的副本，通常不是。
  // }
  // 如果 parameter_block_data 存储的是裸指针，且它们指向的是 Ceres 管理的内存，则不应删除。
  // 如果 parameter_block_data 存储的是你自己的深拷贝数据，且你负责它们的生命周期，那这行可能是正确的。
  // 但根据上下文，很可能它们指向的是优化参数，所以这行是错的。

  // 2. 移除对 cost_function 的删除
  //    因为 ceres::Problem 已经拥有并会删除这些 CostFunction。
  for (int i = 0; i < (int)factors.size(); i++) {
    // 确保 factors[i] 是 ResidualBlockInfo* 类型，且其内部的 cost_function_ 是裸指针
    // ceres::CostFunction *cost_function = factors[i]->cost_function; // 取出指针
    // delete cost_function; // <-- 移除这行！
    // 确保 ResidualBlockInfo 的析构函数也不删除 CostFunction
    delete factors[i]; // <-- 保留这行！因为 MarginalizationInfo 拥有 ResidualBlockInfo 对象
  }
  factors.clear(); // 清空 vector，确保没有野指针
  parameter_block_data.clear(); // 清空 map
}
#将/root/catkin_coco/src/Coco-LIC/src/camera/rgb_map/pointcloud_rgbd.cpp修改如下：
Global_map::Global_map( int if_start_service ): m_should_terminate_thread(false)
{
    m_mutex_pts_vec = std::make_shared< std::mutex >();
    m_mutex_img_pose_for_projection = std::make_shared< std::mutex >();
    m_mutex_recent_added_list = std::make_shared< std::mutex >();
    m_mutex_rgb_pts_in_recent_hitted_boxes = std::make_shared< std::mutex >();
    m_mutex_m_box_recent_hitted = std::make_shared< std::mutex >();
    m_mutex_pts_last_visited = std::make_shared< std::mutex >();
    // Allocate memory for pointclouds
    if ( Common_tools::get_total_phy_RAM_size_in_GB() < 12 )
    {
        scope_color( ANSI_COLOR_RED_BOLD );
        std::this_thread::sleep_for( std::chrono::seconds( 1 ) );
        cout << "+++++++++++++++++++++++++++++++++++++++++++++++++++" << endl;
        cout << "I have detected your physical memory smaller than 12GB (currently: " << Common_tools::get_total_phy_RAM_size_in_GB()
             << "GB). I recommend you to add more physical memory for improving the overall performance of R3LIVE." << endl;
        cout << "+++++++++++++++++++++++++++++++++++++++++++++++++++" << endl;
        std::this_thread::sleep_for( std::chrono::seconds( 5 ) );
        m_rgb_pts_vec.reserve( 1e8 );
    }
    else
    {
        m_rgb_pts_vec.reserve( 1e9 );
    }
    // m_rgb_pts_in_recent_visited_voxels.reserve( 1e6 );
    if ( if_start_service )
    {
        m_thread_service = std::make_shared< std::thread >( &Global_map::service_refresh_pts_for_projection, this );
    }
}
// 在 pointcloud_rgbd.cpp 中
Global_map::~Global_map() {
    // 确保线程在析构前完成其工作
    if (m_thread_service) // **首先检查 shared_ptr 是否有效（不为 nullptr）**
    {
        if (m_thread_service->joinable())
        {
            std::cout << "Global_map destructor: Signaling thread to terminate..." << std::endl; // 调试输出
            m_should_terminate_thread.store(true); // **设置终止标志，原子地写入 true**
            
            // **可选：给线程一个短暂的时间来检测到信号并开始退出过程**
            // std::this_thread::sleep_for(std::chrono::milliseconds(10)); 

            std::cout << "Global_map destructor: Joining m_thread_service..." << std::endl; // 调试输出
            m_thread_service->join(); // 等待线程完成执行
            std::cout << "Global_map destructor: m_thread_service joined." << std::endl; // 调试输出
        } else {
            std::cout << "Global_map destructor: m_thread_service not joinable." << std::endl; // 调试输出
        }
    } else {
        std::cout << "Global_map destructor: m_thread_service is null (thread was not started or already reset)." << std::endl; // 调试输出
    }
}

void Global_map::service_refresh_pts_for_projection()
{
    eigen_q last_pose_q = eigen_q::Identity();
    Common_tools::Timer                timer;
    std::shared_ptr< Image_frame > img_for_projection = std::make_shared< Image_frame >();
    while (!m_should_terminate_thread.load())
    {
        std::this_thread::sleep_for(std::chrono::milliseconds(1));
        if (m_should_terminate_thread.load()) {
            break; // 如果标志已被设置，立即退出循环
        }
        m_mutex_img_pose_for_projection->lock();
         
        *img_for_projection = m_img_for_projection;
        m_mutex_img_pose_for_projection->unlock();
        if (img_for_projection->m_img_cols == 0 || img_for_projection->m_img_rows == 0)
        {
            continue;
        }

        if (img_for_projection->m_frame_idx == m_updated_frame_index)
        {
            continue;
        }
        timer.tic(" ");
        std::shared_ptr<std::vector<std::shared_ptr<RGB_pts>>> pts_rgb_vec_for_projection = std::make_shared<std::vector<std::shared_ptr<RGB_pts>>>();
        if (m_if_get_all_pts_in_boxes_using_mp)
        {
            std::vector<std::shared_ptr<RGB_pts>>  pts_in_recent_hitted_boxes;
            pts_in_recent_hitted_boxes.reserve(1e6);
            std::unordered_set< std::shared_ptr< RGB_Voxel> > boxes_recent_hitted;
            m_mutex_m_box_recent_hitted->lock();
            boxes_recent_hitted = m_voxels_recent_visited;
            m_mutex_m_box_recent_hitted->unlock();

            // get_all_pts_in_boxes(boxes_recent_hitted, pts_in_recent_hitted_boxes);
            m_mutex_rgb_pts_in_recent_hitted_boxes->lock();
            // m_rgb_pts_in_recent_visited_voxels = pts_in_recent_hitted_boxes;
            m_mutex_rgb_pts_in_recent_hitted_boxes->unlock();
        }
        Eigen::aligned_vector<Eigen::Vector3d> fake_points;
        Eigen::aligned_vector<Eigen::Vector2d> fake_pixs;
        selection_points_for_projection(false, fake_points, fake_pixs, img_for_projection, pts_rgb_vec_for_projection.get(), nullptr, 10.0, 1);
        m_mutex_pts_vec->lock();
        m_pts_rgb_vec_for_projection = pts_rgb_vec_for_projection;
        m_updated_frame_index = img_for_projection->m_frame_idx;
        // cout << ANSI_COLOR_MAGENTA_BOLD << "Refresh pts_for_projection size = " << m_pts_rgb_vec_for_projection->size()
        //      << " | " << m_rgb_pts_vec.size()
        //      << ", cost time = " << timer.toc() << ANSI_COLOR_RESET << endl;
        m_mutex_pts_vec->unlock();
        last_pose_q = img_for_projection->m_pose_w2c_q;
    }
     // **可选：添加一条日志，确认线程已退出**
    std::cout << "Global_map::service_refresh_pts_for_projection() thread exiting gracefully." << std::endl;
}
#/root/catkin_coco/src/Coco-LIC/src/camera/rgb_map/pointcloud_rgbd.hpp中新增一行
struct Global_map
{
    int                                                          m_map_major_version = R3LIVE_MAP_MAJOR_VERSION;
    int                                                          m_map_minor_version = R3LIVE_MAP_MINOR_VERSION;
    int                                                          m_if_get_all_pts_in_boxes_using_mp = 1;
    std::vector< RGB_pt_ptr >                    m_rgb_pts_vec;
    // std::vector< RGB_pt_ptr >                    m_rgb_pts_in_recent_visited_voxels;
    std::shared_ptr< std::vector< RGB_pt_ptr> >                  m_pts_rgb_vec_for_projection = nullptr;
    std::shared_ptr< std::mutex >                                m_mutex_pts_vec;
    std::shared_ptr< std::mutex >                                m_mutex_recent_added_list;
    std::shared_ptr< std::mutex >                                m_mutex_img_pose_for_projection;
    std::shared_ptr< std::mutex >                                m_mutex_rgb_pts_in_recent_hitted_boxes;
    std::shared_ptr< std::mutex >                                m_mutex_m_box_recent_hitted;
    std::shared_ptr< std::mutex >                                m_mutex_pts_last_visited;
    Image_frame                                              m_img_for_projection;
    double                                                       m_recent_visited_voxel_activated_time = 0.0;
    bool                                                         m_in_appending_pts = 0;
    int                                                          m_updated_frame_index = 0;
    std::shared_ptr< std::thread >                               m_thread_service;
    std::atomic<bool>                                            m_should_terminate_thread;// <-- 新增这一行
    int                                                          m_if_reload_init_voxel_and_hashed_pts = true;
//。。。后续代码

**Comment by lojmkjd** [comment]
<img width="978" height="980" alt="Image" src="https://github.com/user-attachments/assets/1227fa74-b4f9-41a7-b288-649a2e0c6d92" />

@Geyuwen 谢谢您的解决方案，但是在我仔细对照您的修改后，还是出现了如上的报错；若您有时间，可以告诉我解决办法或是参考的方向吗？十分感谢您！

**Comment by lojmkjd** [comment]
> <img alt="Image" width="978" height="980" src="https://private-user-images.githubusercontent.com/129645177/471786682-1227fa74-b4f9-41a7-b288-649a2e0c6d92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM4NDcxNDEsIm5iZiI6MTc1Mzg0Njg0MSwicGF0aCI6Ii8xMjk2NDUxNzcvNDcxNzg2NjgyLTEyMjdmYTc0LWI0ZjktNDFhNy1iMjg4LTY0OWEyZTBjNmQ5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDczMFQwMzQwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWU4ZTQ0YTI3NWUzNzhjNGYxYzcxNjllMjZlMGYzNTU4ODg3MzI5NGI2NTJlMTJjOTVjYzM4OTc3ODA4NzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LvvPHdz9KBhrZrRPRCH7k1CNSqapXMhCr4LnTZdTNXU">
> [@Geyuwen](https://github.com/Geyuwen) 谢谢您的解决方案，但是在我仔细对照您的修改后，还是出现了如上的报错；若您有时间，可以告诉我解决办法或是参考的方向吗？十分感谢您！

我今天使用ASan进行了调试，希望能为您提供更多的信息：
`
=================================================================
==70284==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x606000337840 in thread T0
    #0 0x7365520cf40f in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:122
    #1 0x5b00ef7c198c in void Eigen::internal::permute_symm_to_fullsymm<2, Eigen::SparseMatrix<double, 0, int>, 0>(Eigen::SparseMatrix<double, 0, int> const&, Eigen::SparseMatrix<Eigen::SparseMatrix<double, 0, int>::Scalar, 0, Eigen::SparseMatrix<double, 0, int>::StorageIndex>&, Eigen::SparseMatrix<double, 0, int>::StorageIndex const*) [clone .constprop.0] (/catkin_coco/devel/lib/cocolic/odometry_node+0x88a98c)
    #2 0x5b00ef7cd452 in Eigen::SimplicialCholeskyBase<Eigen::SimplicialLDLT<Eigen::SparseMatrix<double, 0, int>, 2, Eigen::NaturalOrdering<int> > >::ordering(Eigen::SparseMatrix<double, 0, int> const&, Eigen::SparseMatrix<double, 0, int> const*&, Eigen::SparseMatrix<double, 0, int>&) (/catkin_coco/devel/lib/cocolic/odometry_node+0x896452)
    #3 0x5b00ef7cd7c2 in ceres::internal::EigenSparseCholeskyTemplate<Eigen::SimplicialLDLT<Eigen::SparseMatrix<double, 0, int>, 2, Eigen::NaturalOrdering<int> > >::Factorize(ceres::internal::CompressedRowSparseMatrix*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) (/catkin_coco/devel/lib/cocolic/odometry_node+0x8967c2)
    #4 0x5b00ef69e624 in ceres::internal::SparseCholesky::FactorAndSolve(ceres::internal::CompressedRowSparseMatrix*, double const*, double*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) (/catkin_coco/devel/lib/cocolic/odometry_node+0x767624)
    #5 0x5b00ef69f34f in ceres::internal::SparseNormalCholeskySolver::SolveImpl(ceres::internal::BlockSparseMatrix*, double const*, ceres::internal::LinearSolver::PerSolveOptions const&, double*) (/catkin_coco/devel/lib/cocolic/odometry_node+0x76834f)
    #6 0x5b00ef673866 in ceres::internal::TypedLinearSolver<ceres::internal::BlockSparseMatrix>::Solve(ceres::internal::LinearOperator*, double const*, ceres::internal::LinearSolver::PerSolveOptions const&, double*) (/catkin_coco/devel/lib/cocolic/odometry_node+0x73c866)
    #7 0x5b00ef66020f in ceres::internal::LevenbergMarquardtStrategy::ComputeStep(ceres::internal::TrustRegionStrategy::PerSolveOptions const&, ceres::internal::SparseMatrix*, double const*, double*) (/catkin_coco/devel/lib/cocolic/odometry_node+0x72920f)
    #8 0x5b00ef63a97d in ceres::internal::TrustRegionMinimizer::ComputeTrustRegionStep() (/catkin_coco/devel/lib/cocolic/odometry_node+0x70397d)
    #9 0x5b00ef63ee09 in ceres::internal::TrustRegionMinimizer::Minimize(ceres::internal::Minimizer::Options const&, double*, ceres::Solver::Summary*) (/catkin_coco/devel/lib/cocolic/odometry_node+0x707e09)
    #10 0x5b00ef61291d in ceres::Solver::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) (/catkin_coco/devel/lib/cocolic/odometry_node+0x6db91d)
    #11 0x5b00ef61310d in ceres::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) (/catkin_coco/devel/lib/cocolic/odometry_node+0x6dc10d)
    #12 0x5b00ef2e34df in cocolic::TrajectoryEstimator::Solve(int, bool, int) /catkin_coco/src/Coco-LIC/src/odom/trajectory_estimator.cpp:506
    #13 0x5b00ef19a27e in cocolic::TrajectoryManager::InitTrajWithPropagation() /catkin_coco/src/Coco-LIC/src/odom/trajectory_manager.cpp:309
    #14 0x5b00ef19b697 in cocolic::TrajectoryManager::PredictTrajectory(long, long, long, int, bool) /catkin_coco/src/Coco-LIC/src/odom/trajectory_manager.cpp:271
    #15 0x5b00ef489608 in cocolic::OdometryManager::ProcessLICData() /catkin_coco/src/Coco-LIC/src/odom/odometry_manager.cpp:291
    #16 0x5b00ef493024 in cocolic::OdometryManager::SolveLICO() /catkin_coco/src/Coco-LIC/src/odom/odometry_manager.cpp:256
    #17 0x5b00ef493024 in cocolic::OdometryManager::RunBag() /catkin_coco/src/Coco-LIC/src/odom/odometry_manager.cpp:223
    #18 0x5b00ef04c645 in main /catkin_coco/src/Coco-LIC/src/odometry_node.cpp:44
    #19 0x7365462b0082 in __libc_start_main ../csu/libc-start.c:308
    #20 0x5b00ef055b9d in _start (/catkin_coco/devel/lib/cocolic/odometry_node+0x11eb9d)

0x606000337840 is located 32 bytes inside of 56-byte region [0x606000337820,0x606000337858)
allocated by thread T0 here:
    #0 0x7365520cf808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x5b00ef1d03e8 in Eigen::internal::handmade_aligned_malloc(unsigned long) /usr/include/eigen3/Eigen/src/Core/util/Memory.h:88
    #2 0x5b00ef1d03e8 in Eigen::internal::aligned_malloc(unsigned long) /usr/include/eigen3/Eigen/src/Core/util/Memory.h:164
    #3 0x5b00ef7c1a1c in void Eigen::internal::permute_symm_to_fullsymm<2, Eigen::SparseMatrix<double, 0, int>, 0>(Eigen::SparseMatrix<double, 0, int> const&, Eigen::SparseMatrix<Eigen::SparseMatrix<double, 0, int>::Scalar, 0, Eigen::SparseMatrix<double, 0, int>::StorageIndex>&, Eigen::SparseMatrix<double, 0, int>::StorageIndex const*) [clone .constprop.0] (/catkin_coco/devel/lib/cocolic/odometry_node+0x88aa1c)

SUMMARY: AddressSanitizer: bad-free ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:122 in __interceptor_free
==70284==ABORTING
`

**Comment by weiyi808** [comment]
Hi [Jerry-locker](https://github.com/Jerry-locker),

I modified the thread exit mechanism and projection service in Global_map as follows:

Used std::atomic<bool> for thread flag and ensured join() in destructor.
Added full exception handling and sleep control in service_refresh_pts_for_projection().
Could you review if these changes might introduce:

1. Any race conditions I missed?
2. Performance impact on real-time processing?
3. Conflicts with other parts of the system?

Thanks for your guidance!
`
std::atomic<bool> m_stop_thread_flag = false;
Global_map::~Global_map(){
    m_stop_thread_flag = true;
    if (m_thread_service && m_thread_service->joinable()) {
        m_thread_service->join();  // 确保线程安全退出
    }
};

void Global_map::service_refresh_pts_for_projection()
{
    try {
        eigen_q last_pose_q = eigen_q::Identity();
        Common_tools::Timer timer;
        std::shared_ptr<Image_frame> img_for_projection = std::make_shared<Image_frame>();

        while (!m_stop_thread_flag) 
        {
            std::this_thread::sleep_for(std::chrono::milliseconds(10));
            
            m_mutex_img_pose_for_projection->lock();
            *img_for_projection = m_img_for_projection;
            m_mutex_img_pose_for_projection->unlock();

            if (img_for_projection->m_img_cols == 0 || img_for_projection->m_img_rows == 0)
                continue;

            if (img_for_projection->m_frame_idx == m_updated_frame_index)
                continue;

            timer.tic(" ");

            std::shared_ptr<std::vector<std::shared_ptr<RGB_pts>>> pts_rgb_vec_for_projection =
                std::make_shared<std::vector<std::shared_ptr<RGB_pts>>>();

            if (m_if_get_all_pts_in_boxes_using_mp)
            {
                std::vector<std::shared_ptr<RGB_pts>> pts_in_recent_hitted_boxes;
                pts_in_recent_hitted_boxes.reserve(1e6);

                std::unordered_set<std::shared_ptr<RGB_Voxel>> boxes_recent_hitted;
                m_mutex_m_box_recent_hitted->lock();
                boxes_recent_hitted = m_voxels_recent_visited;
                m_mutex_m_box_recent_hitted->unlock();

                m_mutex_rgb_pts_in_recent_hitted_boxes->lock();
                // m_rgb_pts_in_recent_visited_voxels = pts_in_recent_hitted_boxes;
                m_mutex_rgb_pts_in_recent_hitted_boxes->unlock();
            }

            Eigen::aligned_vector<Eigen::Vector3d> fake_points;
            Eigen::aligned_vector<Eigen::Vector2d> fake_pixs;
            selection_points_for_projection(false, fake_points, fake_pixs, img_for_projection, pts_rgb_vec_for_projection.get(), nullptr, 10.0, 1);

            m_mutex_pts_vec->lock();
            m_pts_rgb_vec_for_projection = pts_rgb_vec_for_projection;
            m_updated_frame_index = img_for_projection->m_frame_idx;
            m_mutex_pts_vec->unlock();

            last_pose_q = img_for_projection->m_pose_w2c_q;
        }

    } catch (const std::exception& e) {
        std::cerr << "[Global_map::service_refresh_pts_for_projection] Exception: " << e.what() << std::endl;
    } catch (...) {
        std::cerr << "[Global_map::service_refresh_pts_for_projection] Unknown exception occurred." << std::endl;
    }
}
`

**Comment by robotvision2BJTU** [comment]
便 Start Coco-LIC Odometry 便
便 Odometry Mode: LiDAR-Inertial-Camera Odometry 便

 The number of multiple LiDARs is 1.

 LoadBag /project/DATA/Fast-LIVO/hku1.bag start at 0 with duration 127.696.

 Static initialization succeeds.

 Trajectory start time: 1577836979704858112 ns.
double free or corruption (out)
[odometry_node_irobot_Super_Server_24318_8258771888953405027-2] process has died [pid 24343, exit code -6, cmd /project/catkin_ws/devel/lib/cocolic/odometry_node __name:=odometry_node_irobot_Super_Server_24318_8258771888953405027 __log:=/root/.ros/log/7de10c42-74e1-11f0-903e-ac1f6bfc8c2c/odometry_node_irobot_Super_Server_24318_8258771888953405027-2.log].
log file: /root/.ros/log/7de10c42-74e1-11f0-903e-ac1f6bfc8c2c/odometry_node_irobot_Super_Server_24318_8258771888953405027-2*.log
================================================================================REQUIRED process [rviz_odom-3] has died!
process has finished cleanly
log file: /root/.ros/log/7de10c42-74e1-11f0-903e-ac1f6bfc8c2c/rviz_odom-3*.log
Initiating shutdown!
================================================================================

**Comment by d5xmbhw2-cpu** [comment]
> <img alt="Image" width="978" height="980" src="https://private-user-images.githubusercontent.com/129645177/471786682-1227fa74-b4f9-41a7-b288-649a2e0c6d92.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njk1OTYwMjIsIm5iZiI6MTc2OTU5NTcyMiwicGF0aCI6Ii8xMjk2NDUxNzcvNDcxNzg2NjgyLTEyMjdmYTc0LWI0ZjktNDFhNy1iMjg4LTY0OWEyZTBjNmQ5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEyOFQxMDIyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjJhOWU4MWRmYjcxNmRmMjU4M2M5MGY0NzU5YzcwOGVmZmY3YTBhMTFhMzg1Y2VlNjYwNTQ2NThjZWUxN2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HFKd8Y3xC5LJRXmvT2WasvzLYAPy2vVVB3dDsgB0IuA">
> [@Geyuwen](https://github.com/Geyuwen) 谢谢您的解决方案，但是在我仔细对照您的修改后，还是出现了如上的报错；若您有时间，可以告诉我解决办法或是参考的方向吗？十分感谢您！

你好,想问下你这个能解决吗,我也试了上面的方法,发现不管用
